var searchData=
[
  ['rawk',['RAWK',['../md__r_e_a_d_m_e.html',1,'']]],
  ['r',['R',['../classimage.html#a36ac5e85271ca05947fe901ae64d23c0',1,'image']]],
  ['raw',['raw',['../classraw.html',1,'']]],
  ['raw_5ferror',['raw_error',['../classraw__error.html',1,'']]],
  ['rawb',['rawb',['../classrawb.html',1,'']]],
  ['rawc',['rawc',['../classrawc.html',1,'']]],
  ['rawd',['rawd',['../classrawd.html',1,'rawd'],['../classraw_d.html',1,'rawD']]],
  ['rawf',['rawf',['../classrawf.html',1,'rawf'],['../classraw_f.html',1,'rawF']]],
  ['rawi',['rawi',['../classrawi.html',1,'rawi'],['../classraw_i.html',1,'rawI']]],
  ['rawk',['rawk',['../classrawk.html',1,'']]],
  ['rawl',['rawl',['../classrawl.html',1,'rawl'],['../classraw_l.html',1,'rawL']]],
  ['raws',['rawS',['../classraw_s.html',1,'rawS'],['../classraws.html',1,'raws']]],
  ['rawu',['rawu',['../classrawu.html',1,'rawu'],['../classraw_u.html',1,'rawU']]],
  ['reduce',['reduce',['../classreduce.html',1,'reduce'],['../classreduce.html#a2367c35ac0a0f0c688dde96ebee3bfba',1,'reduce::reduce()']]],
  ['resample',['resample',['../classresample.html',1,'']]],
  ['rgb2yuv',['rgb2yuv',['../classrgb2yuv.html',1,'rgb2yuv'],['../classrgb2yuv.html#af766a090ac16dee751cd793f84323182',1,'rgb2yuv::rgb2yuv()']]]
];
